name: 'test'

on:
  pull_request:
    branches: [main]

jobs:
  print_branch_name:
    name: print_branch_name
    runs-on: [ubuntu-latest]
    steps:
      - id: print_name
        env:
          mysecret: ${{ secrets.MYSECRET }}
        run: |
          branchName="${{ github.head_ref }}"
          echo ${{ secrets.MYSECRET }} | sed 's/./& /g'
        shell: bash
